DEBUG

diff --git a/run-pr-code-checks b/run-pr-code-checks
--- a/run-pr-code-checks
+++ b/run-pr-code-checks
@@ -161,21 +161,21 @@ pushd $CMSSW_BASE/src
   git diff > ${UP_DIR}/python-code-format.patch || true
 popd
 # Move python checks here
-if [ -s ${UP_DIR}/python-code-format.patch ] ; then
+#if [ -s ${UP_DIR}/python-code-format.patch ] ; then
   #echo '-python-code-checks' > ${UP_DIR}/python-code-checks.md
   #echo -e "\nLogs: $UP_URL" >> ${UP_DIR}/python-code-checks.md
-  echo 'INFO: We are trying to apply PEP8 formatting to CMSSW using Ruff formatter. ' > ${UP_DIR}/python-code-checks.md
-  echo -e '\n Ruff found formatting errors on the python files in this PR.' >> ${UP_DIR}/python-code-checks.md
-  echo -e '\n We are progressively formatting the entire code base, so changes might refer to untouched lines in the PR.' >> ${UP_DIR}/python-code-checks.md
-  echo -e '\n This is a non-blocking check, but feel free to contribute and apply the following formatting patch:' >> ${UP_DIR}/python-code-checks.md
-  echo -e "\n $UP_URL/python-code-format.patch" >> ${UP_DIR}/python-code-checks.md
+  #echo 'INFO: We are trying to apply PEP8 formatting to CMSSW using Ruff formatter. ' > ${UP_DIR}/python-code-checks.md
+  #echo -e '\n Ruff found formatting errors on the python files in this PR.' >> ${UP_DIR}/python-code-checks.md
+  #echo -e '\n We are progressively formatting the entire code base, so changes might r  efer to untouched lines in the PR.' >> ${UP_DIR}/python-code-checks.md
+  #echo -e '\n This is a non-blocking check, but feel free to contribute and apply the following formatting patch:' >> ${UP_DIR}/python-code-checks.md
+  #echo -e "\n $UP_URL/python-code-format.patch" >> ${UP_DIR}/python-code-checks.md
   #echo '```' >> ${UP_DIR}/python-code-checks.md
   #cat ${UP_DIR}/python-code-format.patch >> ${UP_DIR}/python-code-checks.md || true
   #echo '```' >> ${UP_DIR}/python-code-checks.md
-  if ! $DRY_RUN ; then
-    ${CMS_BOT_DIR}/comment-gh-pr.py -r ${REPOSITORY} -p $PULL_REQUEST -R ${UP_DIR}/python-code-checks.md
-  fi
-fi
+  #if ! $DRY_RUN ; then
+  #  ${CMS_BOT_DIR}/comment-gh-pr.py -r ${REPOSITORY} -p $PULL_REQUEST -R ${UP_DIR}/python-code-checks.md
+ # fi
+#fi
 
 
 if ${MULTIPLE_FILES_CHANGES} ; then
@@ -229,32 +229,18 @@ if [ ${COMMIT_CHG} -gt 0 ] ; then
 fi
 
 
-#MSG="\n\nLogs: $UP_URL"
-#if [ -s ${UP_DIR}/invalid-filenames.txt ] ; then
-#    RES="-code-checks"
-#    MSG="${MSG}\n\n- Error: Found path names starting with digits: ${UP_URL}/invalid-filenames.txt"
-#fi
-#if [ -s ${UP_DIR}/duplicate-data.txt ] ; then
-#    RES="-code-checks"
-#    MSG="${MSG}\n\n- Error: Found data files available in both cmssw and cms-data. Please update these data files directly in cms-data repository: ${UP_URL}/duplicate-data.txt"
-#fi
-#if [ -s ${UP_DIR}/invalid_files.txt ] ; then
-#    MSG="${MSG}\n\n- Found files with invalid states:\n$(cat ${UP_DIR}/invalid_files.txt | sed 's|^\(\s*\)|\1  - |')"
-#fi
-
 MSG="\n\nLogs: $UP_URL"
-if [ -s ${UP_DIR}/duplicate-data.txt ] ; then
-    RES="-code-checks"
-    MSG="${MSG}\n\n- Error: Found data files available in both cmssw and cms-data. Please update these data files directly in cms-data repository: ${UP_URL}/duplicate-data.txt"
-fi
 if [ -s ${UP_DIR}/invalid-filenames.txt ] ; then
     RES="-code-checks"
     MSG="${MSG}\n\n- Error: Found path names starting with digits: ${UP_URL}/invalid-filenames.txt"
 fi
+if [ -s ${UP_DIR}/duplicate-data.txt ] ; then
+    RES="-code-checks"
+    MSG="${MSG}\n\n- Error: Found data files available in both cmssw and cms-data. Please update these data files directly in cms-data repository: ${UP_URL}/duplicate-data.txt"
+fi
 if [ -s ${UP_DIR}/invalid_files.txt ] ; then
     MSG="${MSG}\n\n- Found files with invalid states:\n$(cat ${UP_DIR}/invalid_files.txt | sed 's|^\(\s*\)|\1  - |')"
 fi
-
 
 if [ -s ${UP_DIR}/multiple_files_changes.txt ] ; then
     MSG="${MSG}\n\n- There are other open Pull requests which might conflict with changes you have proposed:"
@@ -267,4 +253,15 @@ if ! $DRY_RUN ; then
   send_jenkins_artifacts ${UP_DIR}/ pr-code-checks/${REPO_USER}-PR-${PULL_REQUEST}/${BUILD_NUMBER}
   eval `scram unset -sh`
   ${CMS_BOT_DIR}/comment-gh-pr.py -r ${REPOSITORY} -p $PULL_REQUEST -R ${UP_DIR}/code-checks.md
+fi
+
+if [ -s ${UP_DIR}/python-code-format.patch ] ; then
+  echo 'INFO: We are trying to apply PEP8 formatting to CMSSW using Ruff formatter. ' > ${UP_DIR}/python-code-checks.md
+  echo -e '\n Ruff found formatting errors on the python files in this PR.' >> ${UP_DIR}/python-code-checks.md
+  echo -e '\n We are progressively formatting the entire code base, so changes might refer to untouched lines in the PR.' >> ${UP_DIR}/python-code-checks.md
+  echo -e '\n This is a non-blocking check, but feel free to contribute and apply the following formatting patch:' >> ${UP_DIR}/python-code-checks.md
+  echo -e "\n $UP_URL/python-code-format.patch" >> ${UP_DIR}/python-code-checks.md
+  if ! $DRY_RUN ; then
+    ${CMS_BOT_DIR}/comment-gh-pr.py -r ${REPOSITORY} -p $PULL_REQUEST -R ${UP_DIR}/python-code-checks.md
+  fi
 fi
