[DEBUG]

diff --git a/run-pr-code-checks b/run-pr-code-checks
--- a/run-pr-code-checks
+++ b/run-pr-code-checks
@@ -136,6 +136,18 @@ if $CODE_CHECKS ; then
         ${CMS_BOT_DIR}/comment-gh-pr.py -r ${REPOSITORY} -p $PULL_REQUEST -R ${UP_DIR}/code-checks.md
       fi
       exit 0
+      if [ -s ${UP_DIR}/python-checks.txt ] ; then
+        echo '-python-code-checks' > ${UP_DIR}/python-code-checks.md
+        echo -e "\nLogs: $UP_URL" >> ${UP_DIR}/python-code-checks.md
+        echo -e '\nERROR: Ruff found formatting errors on the python files.' >> ${UP_DIR}/python-code-checks.md
+        echo '```' >> ${UP_DIR}/python-code-checks.md
+        cat ${UP_DIR}/python-checks.txt >> ${UP_DIR}/python-code-checks.md || true
+        echo '```' >> ${UP_DIR}/python-code-checks.md
+        if ! $DRY_RUN ; then
+          send_jenkins_artifacts ${UP_DIR}/ pr-code-checks/${REPO_USER}-PR-${PULL_REQUEST}/${BUILD_NUMBER}
+          ${CMS_BOT_DIR}/comment-gh-pr.py -r ${REPOSITORY} -p $PULL_REQUEST -R ${UP_DIR}/python-code-checks.md
+        fi
+        exit 0
     fi
     if [ -e ${CMSSW_BASE}/tmp/${SCRAM_ARCH}/code-checks-logs ] ; then
       mv ${CMSSW_BASE}/tmp/${SCRAM_ARCH}/code-checks-logs ${UP_DIR}/
@@ -144,7 +156,6 @@ if $CODE_CHECKS ; then
       send_jenkins_artifacts ${UP_DIR}/ pr-code-checks/${REPO_USER}-PR-${PULL_REQUEST}/${BUILD_NUMBER}
       ${CMS_BOT_DIR}/comment-gh-pr.py -r ${REPOSITORY} -p $PULL_REQUEST -R ${UP_DIR}/python-code-checks.md
     fi
-
     pushd $CMSSW_BASE/src
       git diff > ${UP_DIR}/code-checks.patch
       if [ -s ${UP_DIR}/code-checks.patch ] ; then
@@ -220,6 +231,7 @@ if [ ${COMMIT_CHG} -gt 0 ] ; then
     HOW_TO_RUN="${HOW_TO_RUN}\ne.g. \`curl -k https://cmssdt.cern.ch/SDT/${JENKINS_PREFIX_STR}code-checks/${REPO_USER}-PR-${PULL_REQUEST}/${BUILD_NUMBER}/python-code-format.patch | patch -p1\`"
     HOW_TO_RUN="${HOW_TO_RUN}\nYou can also run \`python3 PFA.py <file> or python3 run-python-format.py --inputfile <code-checks-files.txt> --cmsswbase <basepath>\` to apply Python code formatting directly"
   fi
+
 
 
 MSG="\n\nLogs: $UP_URL"
