Moved python checks

diff --git a/run-pr-code-checks b/run-pr-code-checks
--- a/run-pr-code-checks
+++ b/run-pr-code-checks
@@ -128,22 +128,6 @@ if $CODE_CHECKS ; then
         ${CMS_BOT_DIR}/comment-gh-pr.py -r ${REPOSITORY} -p $PULL_REQUEST -R ${UP_DIR}/code-checks.md
       fi
       #exit 0
-
-      if [ -s ${UP_DIR}/python-code-format.patch ] ; then
-        #echo '-python-code-checks' > ${UP_DIR}/python-code-checks.md
-        #echo -e "\nLogs: $UP_URL" >> ${UP_DIR}/python-code-checks.md
-        echo 'INFO: We are trying to apply PEP8 formatting to CMSSW using Ruff formatter. ' > ${UP_DIR}/python-code-checks.md
-        echo -e '\n Ruff found formatting errors on the python files in this PR.' >> ${UP_DIR}/python-code-checks.md
-        echo -e '\n We are progressively formatting the entire code base, so changes might refer to untouched lines in the PR.' >> ${UP_DIR}/python-code-checks.md
-        echo -e '\n This is a non-blocking check, but feel free to contribute and apply the following formatting patch:' >> ${UP_DIR}/python-code-checks.md
-        echo -e "\n $UP_URL/python-code-format.patch" >> ${UP_DIR}/python-code-checks.md
-        #echo '```' >> ${UP_DIR}/python-code-checks.md
-        #cat ${UP_DIR}/python-code-format.patch >> ${UP_DIR}/python-code-checks.md || true
-        #echo '```' >> ${UP_DIR}/python-code-checks.md
-        if ! $DRY_RUN ; then
-          ${CMS_BOT_DIR}/comment-gh-pr.py -r ${REPOSITORY} -p $PULL_REQUEST -R ${UP_DIR}/python-code-checks.md
-        fi
-      fi
       exit 0
     fi
     if [ -e ${CMSSW_BASE}/tmp/${SCRAM_ARCH}/code-checks-logs ] ; then
@@ -166,10 +150,9 @@ if $CODE_FORMAT ; then
     if [ -s ${UP_DIR}/code-format-files.txt ] ; then
       scram build -k -j $NUM_PROC code-format USER_CODE_FORMAT_FILE="${UP_DIR}/code-format-files.txt" > ${UP_DIR}/code-format.log 2>&1
       pushd $CMSSW_BASE/src
-        git restore .
         git diff > ${UP_DIR}/code-format.patch
         cat ${UP_DIR}/code-format.patch
-        if [ $(cat ${UP_DIR}/code-format.patch | wc -l) -gt 0 ] ; then
+        if [ -s ${UP_DIR}/code-format.patch ] ; then
           git commit -a -m 'auto applied code-formats changes'
           let COMMIT_CHG=${COMMIT_CHG}+1
         fi
@@ -178,6 +161,22 @@ if $CODE_FORMAT ; then
   fi
 fi
 
+# Move python checks here
+if [ -s ${UP_DIR}/python-code-format.patch ] ; then
+  #echo '-python-code-checks' > ${UP_DIR}/python-code-checks.md
+  #echo -e "\nLogs: $UP_URL" >> ${UP_DIR}/python-code-checks.md
+  echo 'INFO: We are trying to apply PEP8 formatting to CMSSW using Ruff formatter. ' > ${UP_DIR}/python-code-checks.md
+  echo -e '\n Ruff found formatting errors on the python files in this PR.' >> ${UP_DIR}/python-code-checks.md
+  echo -e '\n We are progressively formatting the entire code base, so changes might refer to untouched lines in the PR.' >> ${UP_DIR}/python-code-checks.md
+  echo -e '\n This is a non-blocking check, but feel free to contribute and apply the following formatting patch:' >> ${UP_DIR}/python-code-checks.md
+  echo -e "\n $UP_URL/python-code-format.patch" >> ${UP_DIR}/python-code-checks.md
+  #echo '```' >> ${UP_DIR}/python-code-checks.md
+  #cat ${UP_DIR}/python-code-format.patch >> ${UP_DIR}/python-code-checks.md || true
+  #echo '```' >> ${UP_DIR}/python-code-checks.md
+  if ! $DRY_RUN ; then
+    ${CMS_BOT_DIR}/comment-gh-pr.py -r ${REPOSITORY} -p $PULL_REQUEST -R ${UP_DIR}/python-code-checks.md
+  fi
+fi
 
 
 if ${MULTIPLE_FILES_CHANGES} ; then
