Moved python bot comments

diff --git a/run-pr-code-checks b/run-pr-code-checks
--- a/run-pr-code-checks
+++ b/run-pr-code-checks
@@ -156,26 +156,26 @@ if $CODE_FORMAT ; then
 fi
 
 # run python checks
-python3 ../cms-bot/run-python-format.py --inputfile "${UP_DIR}/code-checks-files.txt" --cmsswbase "${CMSSW_BASE}/src"
-pushd $CMSSW_BASE/src
-  git diff > ${UP_DIR}/python-code-format.patch || true
-popd
+#python3 ../cms-bot/run-python-format.py --inputfile "${UP_DIR}/code-checks-files.txt" --cmsswbase "${CMSSW_BASE}/src"
+#pushd $CMSSW_BASE/src
+#  git diff > ${UP_DIR}/python-code-format.patch || true
+#popd
 # Move python checks here
-if [ -s ${UP_DIR}/python-code-format.patch ] ; then
+#if [ -s ${UP_DIR}/python-code-format.patch ] ; then
   #echo '-python-code-checks' > ${UP_DIR}/python-code-checks.md
   #echo -e "\nLogs: $UP_URL" >> ${UP_DIR}/python-code-checks.md
-  echo 'INFO: We are trying to apply PEP8 formatting to CMSSW using Ruff formatter. ' > ${UP_DIR}/python-code-checks.md
-  echo -e '\n Ruff found formatting errors on the python files in this PR.' >> ${UP_DIR}/python-code-checks.md
-  echo -e '\n We are progressively formatting the entire code base, so changes might refer to untouched lines in the PR.' >> ${UP_DIR}/python-code-checks.md
-  echo -e '\n This is a non-blocking check, but feel free to contribute and apply the following formatting patch:' >> ${UP_DIR}/python-code-checks.md
-  echo -e "\n $UP_URL/python-code-format.patch" >> ${UP_DIR}/python-code-checks.md
+  #echo 'INFO: We are trying to apply PEP8 formatting to CMSSW using Ruff formatter. ' > ${UP_DIR}/python-code-checks.md
+  #echo -e '\n Ruff found formatting errors on the python files in this PR.' >> ${UP_DIR}/python-code-checks.md
+  #echo -e '\n We are progressively formatting the entire code base, so changes might refer to untouched lines in the PR.' >> ${UP_DIR}/python-code-checks.md
+  #echo -e '\n This is a non-blocking check, but feel free to contribute and apply the following formatting patch:' >> ${UP_DIR}/python-code-checks.md
+  #echo -e "\n $UP_URL/python-code-format.patch" >> ${UP_DIR}/python-code-checks.md
   #echo '```' >> ${UP_DIR}/python-code-checks.md
   #cat ${UP_DIR}/python-code-format.patch >> ${UP_DIR}/python-code-checks.md || true
   #echo '```' >> ${UP_DIR}/python-code-checks.md
-  if ! $DRY_RUN ; then
-    ${CMS_BOT_DIR}/comment-gh-pr.py -r ${REPOSITORY} -p $PULL_REQUEST -R ${UP_DIR}/python-code-checks.md
-  fi
-fi
+  #if ! $DRY_RUN ; then
+    #${CMS_BOT_DIR}/comment-gh-pr.py -r ${REPOSITORY} -p $PULL_REQUEST -R ${UP_DIR}/python-code-checks.md
+  #fi
+#fi
 
 
 if ${MULTIPLE_FILES_CHANGES} ; then
@@ -219,7 +219,6 @@ if [ ${COMMIT_CHG} -gt 0 ] ; then
   fi
 
   # Added Python code format instructions, i just followed ^
-  # Ask Andrea about this part, not sure if works
   if [ -s ${UP_DIR}/python-code-format.patch ] ; then
     HOW_TO_RUN="${HOW_TO_RUN}\n\n- **python-code-format**:"
     HOW_TO_RUN="${HOW_TO_RUN}\nhttps://cmssdt.cern.ch/SDT/${JENKINS_PREFIX_STR}code-checks/${REPO_USER}-PR-${PULL_REQUEST}/${BUILD_NUMBER}/python-code-format.patch"
@@ -227,6 +226,29 @@ if [ ${COMMIT_CHG} -gt 0 ] ; then
     HOW_TO_RUN="${HOW_TO_RUN}\nYou can also run \`python3 PFA.py <file> or python3 run-python-format.py --inputfile <code-checks-files.txt> --cmsswbase <basepath>\` to apply Python code formatting directly"
   fi
 fi
+
+# run python checks, new thing
+python3 ../cms-bot/run-python-format.py --inputfile "${UP_DIR}/code-checks-files.txt" --cmsswbase "${CMSSW_BASE}/src"
+pushd $CMSSW_BASE/src
+  git diff > ${UP_DIR}/python-code-format.patch || true
+popd
+# Move python checks here
+if [ -s ${UP_DIR}/python-code-format.patch ] ; then
+  #echo '-python-code-checks' > ${UP_DIR}/python-code-checks.md
+  #echo -e "\nLogs: $UP_URL" >> ${UP_DIR}/python-code-checks.md
+  echo 'INFO: We are trying to apply PEP8 formatting to CMSSW using Ruff formatter. ' > ${UP_DIR}/python-code-checks.md
+  echo -e '\n Ruff found formatting errors on the python files in this PR.' >> ${UP_DIR}/python-code-checks.md
+  echo -e '\n We are progressively formatting the entire code base, so changes might refer to untouched lines in the PR.' >> ${UP_DIR}/python-code-checks.md
+  echo -e '\n This is a non-blocking check, but feel free to contribute and apply the following formatting patch:' >> ${UP_DIR}/python-code-checks.md
+  echo -e "\n $UP_URL/python-code-format.patch" >> ${UP_DIR}/python-code-checks.md
+  #echo '```' >> ${UP_DIR}/python-code-checks.md
+  #cat ${UP_DIR}/python-code-format.patch >> ${UP_DIR}/python-code-checks.md || true
+  #echo '```' >> ${UP_DIR}/python-code-checks.md
+  if ! $DRY_RUN ; then
+    ${CMS_BOT_DIR}/comment-gh-pr.py -r ${REPOSITORY} -p $PULL_REQUEST -R ${UP_DIR}/python-code-checks.md
+  fi
+fi
+
 
 
 MSG="\n\nLogs: $UP_URL"
