FIx github integration

diff --git a/run-pr-code-checks b/run-pr-code-checks
--- a/run-pr-code-checks
+++ b/run-pr-code-checks
@@ -117,11 +117,7 @@ if $CODE_CHECKS ; then
     python3 ../cms-bot/run-python-format.py --inputfile "${UP_DIR}/code-checks-files.txt" --cmsswbase "${CMSSW_BASE}/src"
     # After Python code formatting and linting, not sure if correct place
     pushd $CMSSW_BASE/src
-        git diff > ${UP_DIR}/python-code-format.patch
-      if [ -s ${UP_DIR}/python-code-format.patch ] ; then
-        git commit -a -m 'auto applied python code-format changes'
-        let COMMIT_CHG=${COMMIT_CHG}+1
-      fi
+        git diff > ${UP_DIR}/python-code-format.patch || true
     popd
 
     if $ERR ; then
@@ -135,20 +131,23 @@ if $CODE_CHECKS ; then
         send_jenkins_artifacts ${UP_DIR}/ pr-code-checks/${REPO_USER}-PR-${PULL_REQUEST}/${BUILD_NUMBER}
         ${CMS_BOT_DIR}/comment-gh-pr.py -r ${REPOSITORY} -p $PULL_REQUEST -R ${UP_DIR}/code-checks.md
       fi
-      exit 0
-      if [ -s ${UP_DIR}/python-checks.txt ] ; then
-        echo '-python-code-checks' > ${UP_DIR}/python-code-checks.md
-        echo -e "\nLogs: $UP_URL" >> ${UP_DIR}/python-code-checks.md
-        echo -e '\nERROR: Ruff found formatting errors on the python files.' >> ${UP_DIR}/python-code-checks.md
-        echo '```' >> ${UP_DIR}/python-code-checks.md
-        cat ${UP_DIR}/python-checks.txt >> ${UP_DIR}/python-code-checks.md || true
-        echo '```' >> ${UP_DIR}/python-code-checks.md
+      #exit 0
+      if [ -s ${UP_DIR}/python-code-format.patch ] ; then
+        #echo '-python-code-checks' > ${UP_DIR}/python-code-checks.md
+        #echo -e "\nLogs: $UP_URL" >> ${UP_DIR}/python-code-checks.md
+        echo 'INFO: We are trying to apply PEP8 formatting to CMSSW using Ruff formatter. ' > ${UP_DIR}/python-code-checks.md
+        echo -e '\n Ruff found formatting errors on the python files in this PR.' >> ${UP_DIR}/python-code-checks.md
+        echo -e '\n We are progressively formatting the entire code base, so changes might refer to untouched lines in the PR.' >> ${UP_DIR}/python-code-checks.md
+        echo -e '\n This is a non-blocking check, but feel free to contribute and apply the following formatting patch:' >> ${UP_DIR}/python-code-checks.md
+        echo -e "\n $UP_URL/python-code-format.patch" >> ${UP_DIR}/python-code-checks.md
+        #echo '```' >> ${UP_DIR}/python-code-checks.md
+        #cat ${UP_DIR}/python-code-format.patch >> ${UP_DIR}/python-code-checks.md || true
+        #echo '```' >> ${UP_DIR}/python-code-checks.md
         if ! $DRY_RUN ; then
-          send_jenkins_artifacts ${UP_DIR}/ pr-code-checks/${REPO_USER}-PR-${PULL_REQUEST}/${BUILD_NUMBER}
           ${CMS_BOT_DIR}/comment-gh-pr.py -r ${REPOSITORY} -p $PULL_REQUEST -R ${UP_DIR}/python-code-checks.md
         fi
-        exit 0
       fi
+      exit 0
     fi
     if [ -e ${CMSSW_BASE}/tmp/${SCRAM_ARCH}/code-checks-logs ] ; then
       mv ${CMSSW_BASE}/tmp/${SCRAM_ARCH}/code-checks-logs ${UP_DIR}/
